const plugin = require('tailwindcss/plugin');

const defaultBtnStyle = {
  paddingLeft: '24px',
  paddingRight: '24px',
  height: '44px',
  borderRadius: '8px',
};

const defaultBtnStyleWFull = {
  paddingTop: '12px',
  paddingBottom: '12px',
  width: '528px',
  height: '44px',
  borderRadius: '8px',
};

module.exports = {
  purge: [
    './public/**/*.html',
    './components/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      margin: {
        '-384px': '-384px',
        '-224px': '-224px',
        '-167px': '-167px',
        '-58px': '-58px',
        '-24px': '-24px',
        '-12px': '-12px',
        '-8px': '-8px',
        '-2px': '-2px',
        '-px': '-1px',
        '3/2px': '1.5px',
        '2px': '2px',
        '4px': '4px',
        '6px': '6px',
        '8px': '8px',
        '12px': '12px',
        '14px': '14px',
        '16px': '16px',
        '18px': '18px',
        '20px': '20px',
        '24px': '24px',
        '27px': '27px',
        '32px': '32px',
        '36px': '36px',
        '40px': '40px',
        '48px': '48px',
        '72px': '72px',
        '80px': '80px',
      },
      padding: {
        '3/2px': '3/2px',
        '2px': '2px',
        '4px': '4px',
        '8px': '8px',
        '12px': '12px',
        '16px': '16px',
        '18px': '18px',
        '24px': '24px',
        '30px': '30px',
        '32px': '32px',
        '36px': '36px',
        '40px': '40px',
        '54px': '60px',
      },
      space: {
        '24px': '24px',
      },
      inset: {
        '-70px': '-70px',
        '-64px': '-64px',
        '-55px': '-55px',
        '-26px': '-26px',
        '-22px': '-22px',
        '-12px': '-12px',
        '12px': '12px',
        '16px': '16px',
        '24px': '24px',
        '40px': '40px',
        '44px': '44px',
        '80px': '80px',
        // '66px': '66px',
      },
      height: {
        '1px': '1px',
        '2px': '2px',
        '3px': '3px',
        '12px': '12px',
        '14px': '14px',
        '15px': '15px',
        '18px': '18px',
        '20px': '20px',
        '22px': '22px',
        '24px': '24px',
        '30px': '30px',
        '32px': '32px',
        '35px': '35px',
        '36px': '36px',
        '38px': '38px',
        '40px': '40px',
        '44px': '44px',
        '48px': '48px',
        '63px': '63px',
        '66px': '65px',
        '68px': '68px',
        '72px': '72px',
        '92px': '92px',
        '140px': '140px',
        '190px': '190px',
        '240px': '240px',
        '450px': '450px',
        '590px': '590px',
        '660px': '660px',
        '900px': '900px',
      },
      width: {
        '4px': '4px',
        '14px': '14px',
        '15px': '15px',
        '20px': '20px',
        '22px': '22px',
        '24px': '24px',
        '30px': '30px',
        '32px': '32px',
        '35px': '35px',
        '36px': '36px',
        '40px': '40px',
        '44px': '44px',
        '49px': '49px',
        '62px': '62px',
        '72px': '72px',
        '75px': '75px',
        '84px': '84px',
        '88px': '88px',
        '92px': '92px',
        '100px': '100px',
        '120px': '120px',
        '124px': '124px',
        '135px': '135px',
        '150px': '150px',
        '164px': '164px',
        '200px': '200px',
        '204px': '204px',
        '220px': '220px',
        '248px': '248px',
        '300px': '300px',
        '356px': '356px',
        '412px': '412px',
        '432px': '432px',
        '460px': '460px',
        '528px': '528px',
        '564px': '564px',
        '660px': '660px',
        '880px': '880px',
        '1440px': '1440px',
        '30p': '30%',
        '2/9': '22.22%',
        '2/7': '28%',
        '3/10': '30%',
        '3/5': '60%',
      },
      maxWidth: {
        '40px': '40px',
        '620px': '620px',
        '2/9': '22.22%',
        '1/2': '50%',
        '1440px': '1440px',
      },
      maxHeight: {
        '200px': '200px',
        '500px': '500px',
      },
      minWidth: {
        '3/5': '60%',
      },
      minHeight: {
        '120px': '120px',
      },
      borderWidth: {
        '1/4': '0.25px',
        '1/2': '0.5px',
        '3/2': '1.5px',
      },
      borderRadius: {
        '1px': '1px',
        '2px': '2px',
        '4px': '4px',
        '6px': '6px',
        '8px': '8px',
      },
      zIndex: {
        90: 90,
        100: 100,
        9999: 9999,
      },
      ringWidth: {},
      colors: {
        primary: '#007aff',
        primaryPressed: '#007aff80',
        primaryDisabled: '#007aff3d',
        primarySelected: '#007aff14',
        primarySelectedPure: '#b4d8ff',
        primaryHovered: '#007aff1a',
        primaryHoveredPure: '#eaf5ff',
        secondary: '#eb4d3d',
        secondaryPressed: '#eb4d3d80',
        secondaryDisabled: '#eb4d3d3d',
        tertiary: '#ffd60a',
        tertiaryPressed: '#ffd60a80',
        tertiaryDisabled: '#ffd60a3d',
        tertiarySelected: '#ffd60a14',
        backgroundPrimary: '#f9f9f9',
        backgroundSecondary: '#fff',
        backgroundTertiary: '#f9f9f9',
        fontPrimary: '#000000DF',
        fontSecondary: '#00000066',
        fontTertiary: '#0000003d',
        backgroundLoading: '#00000014',
        separator: '#eaeaea',
        overlayWeb1: '#f9f9f9',
        overlayWeb2: '#f1f1f1',
        green: '#30d158',
        teal: '#64b2ff',
        indigo: '#575acf',
        purple: '#bf5af2',
        pink: '#f86f8b',
        orange: '#ff9f0a',
        yellow: '#ffd60a',
        brown: '#ad5c00',
        // custom colors
        carminePink: '#eb4d3d',
        watermelonPink: '#f86f8b',
        tyrianPurple: '#bf5af2',
        iris: '#575acf',
        deepSkyBlue: '#007aff',
        crystalBlue: '#64b2ff',
        malachite: '#30d158',
        rubberYellow: '#ffd60a',
        orangePeel: '#ff9f0a',
        ginger: '#ad5c00',
        grayBlack: '#00000066',
        darkBlack: '#000000DF',
        black: '#000',
        yellowOp3: '#ffd60a4d',
        yellowWeek: '#fff3b5',
        blueWeek: '#b2d7ff',
        blueOp3: '#007aff4d',
      },
      fontSize: {
        '13px': ['13px', '15px'],
      },
      fontFamily: {
        fontEn: ['Roboto'],
        fontJp: ['NotaSansCJKjp'],
      },
      letterSpacing: {
        xNormal: 0.06,
        xNarrow: -0.15,
        xWide: 0.38,
      },
      lineHeight: {
        xHigher: 24,
        xHigh: 20,
        xNormal: 16,
        xLow: 8,
      },
      aspectRatio: {},
      translate: {
        fullX2: '200%',
        fullX3: '300%',
        fullX4: '400%',
      },
      boxShadow: {
        menu: '0 0 12px 0 rgba(0, 0, 0, 0.12)',
        button: '0 0 4px 0 rgba(0, 0, 0, 0.12)',
      },
      scale: {
        125: '1.25',
      },
      opacity: {
        8: '0.08',
      },
    },
    fill: {},
    borderStyles: {},
    ringColor: {},
  },
  variants: {
    extend: {
      backgroundColor: ['active'],
      boxShadow: ['active'],
      opacity: ['active'],
      backgroundOpacity: ['hover', 'active'],
    },
    opacity: ({ after }) => after(['disabled']),
  },
  plugins: [
    plugin(function ({ addBase, theme }) {
      addBase({
        '.input-primary': {
          padding: '12px 16px',
          width: '528px',
          height: '44px',
          borderRadius: '8px',
          backgroundColor: theme('colors.backgroundPrimary'),
        },
        '.input-digit': {
          padding: '10px',
          height: '44px',
          width: '35px',
          borderRadius: '8px',
          backgroundColor: theme('colors.backgroundPrimary'),
        },
        '.button-primary': {
          ...defaultBtnStyleWFull,
          backgroundColor: theme('colors.primary'),
          color: theme('colors.backgroundSecondary'),
        },
        '.button-transparent': {
          ...defaultBtnStyleWFull,
          border: 'solid 0.5px',
          borderColor: theme('colors.separator'),
          backgroundColor: theme('colors.backgroundSecondary'),
          color: theme('colors.fontPrimary'),
        },
        '.btn--default': {
          ...defaultBtnStyle,
          backgroundColor: theme('colors.primary'),
          color: theme('colors.backgroundSecondary'),
        },
        // * align classes
        '.flex-row--between': {
          display: 'flex',
          flexDirection: 'row',
          justifyContent: 'space-between',
          alignItems: 'center',
        },
        '.flex-row--end': {
          display: 'flex',
          flexDirection: 'row',
          justifyContent: 'flex-end',
          alignItems: 'center',
        },
        '.flex-xy-center': {
          display: 'flex',
          flexDirection: 'row',
          justifyContent: 'center',
          alignItems: 'center',
        },
        // * border classes
        '.border-box': {
          borderRadius: '8px',
          border: 'solid 0.5px',
          borderColor: theme('colors.separator'),
        },
        // * font classes
        '.bigger-title-en': {
          fontSize: '22px',
          letterSpacing: 0.35,
          fontWeight: '500',
          fontFamily: theme('fontFamily.fontEn'),
        },
        '.big-title': {
          fontSize: '20px',
          letterSpacing: 0.38,
          fontWeight: '600',
          fontFamily: theme('fontFamily.fontJp'),
          // lineHeight: 24,
        },
        '.big-title-en': {
          fontSize: '20px',
          letterSpacing: 0.38,
          fontWeight: '600',
          fontFamily: theme('fontFamily.fontEn'),
          // lineHeight: 24,
        },
        '.big-title-light': {
          fontSize: '20px',
          letterSpacing: 0.38,
          fontWeight: '400',
          fontFamily: theme('fontFamily.fontJp'),
        },
        '.med-title': {
          fontSize: '16px',
          letterSpacing: -0.15,
          fontWeight: '400',
          fontFamily: theme('fontFamily.fontJp'),
        },
        '.med-title-en': {
          fontSize: '18px',
          letterSpacing: -0.15,
          fontWeight: '400',
          fontFamily: theme('fontFamily.fontJp'),
        },
        '.title': {
          fontSize: '14px',
          letterSpacing: -0.15,
          fontWeight: '600',
          fontFamily: theme('fontFamily.fontJp'),
          // lineHeight: 24,
        },
        '.title-en': {
          fontSize: '16px',
          letterSpacing: -0.32,
          fontFamily: theme('fontFamily.fontEn'),
          // lineHeight: 24,
        },
        '.subtitle': {
          fontSize: '12px',
          letterSpacing: 0,
          fontWeight: '600',
          fontFamily: theme('fontFamily.fontJp'),
          // lineHeight: 20,
        },
        '.subtitle-en': {
          fontSize: '14px',
          letterSpacing: -0.15,
          fontWeight: '500',
          fontFamily: theme('fontFamily.fontEn'),
          // lineHeight: 20,
        },
        '.body1': {
          fontSize: '14px',
          letterSpacing: -0.15,
          fontWeight: '400',
          fontFamily: theme('fontFamily.fontJp'),
          // lineHeight: 20,
        },
        '.body1-en': {
          fontSize: '16px',
          letterSpacing: -0.32,
          fontWeight: '400',
          fontFamily: theme('fontFamily.fontEn'),
          // lineHeight: 20,
        },
        '.body2': {
          fontSize: '12px',
          letterSpacing: 0,
          fontWeight: '400',
          fontFamily: theme('fontFamily.fontJp'),
          // lineHeight: 20,
        },
        '.body2-en': {
          fontSize: '14px',
          letterSpacing: -0.15,
          fontWeight: '400',
          fontFamily: theme('fontFamily.fontEn'),
          // lineHeight: 20,
        },
        '.body3-en': {
          fontSize: '15px',
          letterSpacing: -0.24,
          fontWeight: '500',
          fontFamily: theme('fontFamily.fontEn'),
        },
        '.body3': {
          fontSize: '13px',
          letterSpacing: -0.08,
          fontWeight: 400,
          fontFamily: theme('fontFamily.fontJp'),
        },
        '.button': {
          fontSize: '14px',
          letterSpacing: 0,
          fontWeight: '400',
          fontFamily: theme('fontFamily.fontJp'),
          // lineHeight: 20,
        },
        '.button-en': {
          fontSize: '16px',
          letterSpacing: -0.32,
          fontWeight: '400',
          fontFamily: theme('fontFamily.fontEn'),
          // lineHeight: 20,
        },
        '.caption2': {
          fontSize: '10px',
          letterSpacing: 0.06,
          fontWeight: '600',
          fontFamily: theme('fontFamily.fontJp'),
          // lineHeight: 16,
        },
        '.caption2-light': {
          fontSize: '10px',
          letterSpacing: 0.06,
          fontWeight: '400',
          fontFamily: theme('fontFamily.fontJp'),
        },
        '.caption2-en': {
          fontSize: '12px',
          letterSpacing: 0,
          fontWeight: '500',
          fontFamily: theme('fontFamily.fontEn'),
          // lineHeight: 16,
        },
        '.caption2-en-light': {
          fontSize: '12px',
          letterSpacing: 0,
          fontWeight: '400',
          fontFamily: theme('fontFamily.fontEn'),
        },
        '.caption3': {
          fontSize: '8px',
          letterSpacing: 0,
          fontWeight: '400',
          fontFamily: theme('fontFamily.fontJp'),
          // lineHeight: 8,
        },
        '.caption3-en': {
          fontSize: '10px',
          letterSpacing: 0.06,
          fontWeight: '500',
          fontFamily: theme('fontFamily.fontEn'),
          // lineHeight: 8,
        },
        '.caption4': {
          fontSize: '7px',
          letterSpacing: 0,
          fontWeight: '400',
          fontFamily: theme('fontFamily.fontJp'),
        },
        '.font-en': {
          fontFamily: theme('fontFamily.fontEn'),
        },
        '.font-jp': {
          fontFamily: theme('fontFamily.fontJp'),
        },
        // * box classes
        '.setting-header': {
          paddingLeft: '24px',
          paddingRight: '24px',
          height: '72px',
          width: '100%',
          borderBottomWidth: '1px',
          borderBottomColor: theme('colors.separator'),
          display: 'flex',
          flexDirection: 'row',
          justifyContent: 'space-between',
          alignItems: 'center',
        },
        '.flex-grow': {
          flexGrow: 1,
          flexShrink: 0,
        },
      });
    }),
    require('@tailwindcss/line-clamp'),
  ],
};
